#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [ ! -f $DIR/../cache/$1.mp3 ]; then
	echo 'FILE NOT FOUND.'
	exit 1
else
	echo 'FILE FOUND.'
	rm $DIR/../cache/$1.mp3
	echo 'FILE DELETED.'
fi
